### ISSUE TITLE
多次点击Send后再Start Consumer就崩溃了

### ISSUE THREAD

**Issue by 70kg** [drakeet/MailOtto#3]
不知道你有没有发现这个问题，我觉得这个应该很容易发现。。难道是我的问题？
` Caused by: java.util.ConcurrentModificationException
                                                                              at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
                                                                              at me.drakeet.mailotto.Mailbox.dispatchMails(Mailbox.java:171)`

如果把`mailsToDispatch`的`LinkedList`改成`CopyOnWriteArrayList`就可以，或者修改遍历方法，不用for-each，也是可以解决的，但是似乎也没有在迭代的时候去add,为什么会抛出这个异常。。有些不理解，希望解释一下，感谢。

**Comment by drakeet** [comment]
感谢反馈，我明天查查

**Comment by CaMnter** [comment]
@70kg  遍历LinkedList<Mail>中直接删除Mail对象是有问题的，可以根据index删除。 准确地说是所有List都不能在for-each中remove对象。

LinkedList：
```
    @Override
    public E remove(int location) {
        if (location >= 0 && location < size) {
            Link<E> link = voidLink;
            if (location < (size / 2)) {
                for (int i = 0; i <= location; i++) {
                    link = link.next;
                }
            } else {
                for (int i = size; i > location; i--) {
                    link = link.previous;
                }
            }
            Link<E> previous = link.previous;
            Link<E> next = link.next;
            previous.next = next;
            next.previous = previous;
            size--;
            modCount++;
            return link.data;
        }
        throw new IndexOutOfBoundsException();
    }

    @Override
    public boolean remove(Object object) {
        return removeFirstOccurrenceImpl(object);
    }
```
