### ISSUE TITLE
Mail 中 content 的类型和目标对象注解的接收方法

### ISSUE THREAD

**Issue by twiceyuan** [drakeet/MailOtto#4]
你好，看了这个项目感觉很有意思，有两个地方请教一下：Mail 的 content 类型能否定义为泛型？这样取的时候就不需要强制类型转换了；还有注解的接收方法能否直接参数定义为 Mail 中 content 的类型，感觉这样更方便一些（用起来更像 Otto）。

如果有描述不清楚的地方，我自己 fork 了改了一下这两个地方 https://github.com/twiceyuan/MailOtto/commit/c67613b4f9ba68bb53de872055bfc3230b723724

**Comment by drakeet** [comment]
是的，目前还比较初期，Mail 模型还需要开发，这个是接下来要做的，以及 check 和一些状态的回调，如果有什么还建议，欢迎讨论
