### ISSUE TITLE
在Application  post后如果重复开启一个界面  OnMailReceived将不会执行  

### ISSUE THREAD

**Issue by goodluckforme** [drakeet/MailOtto#8]
在Application  post后如果重复开启一个界面（如详情页）
即使在oncreate方法中加入了 
Mailbox.getInstance().atHome(this)
 OnMailReceived也不会执行    
@OnMailReceived
    fun onMailReceived(mail: Mail) {
        val aMapLocation = mail.content as AMapLocation
        selsellinfoParm.coordinate = "${aMapLocation.longitude},${aMapLocation.latitude}"
    }

**Comment by drakeet** [comment]
重复开启的话，会被第一个订阅者消费掉，因此第二个订阅者无法再收到内容。
另外，这个项目已经停止维护并且废弃了，如果依赖它，请改为使用 RxJava 或 EventBus 获得实现。

**Comment by goodluckforme** [comment]
为什么要废弃呢？ 其实我看中的就是这个框架的懒加载机制   evenbus实现不了
比如我打开一个详情页  关闭 再打开  应该在可以继续回调OnMailReceived才对是吧 ？
我觉得稍加修改还是很好用的。

**Comment by drakeet** [comment]
EventBus 现在支持 sticky 事件，可以实现 MailOtto 的内容。MailOtto 还是比较初级、有限，而且由于 RxJava 和 EventBus 皆能完美实现这个项目原先的功能，因此觉得已经没有再花时间去维护的必要了，时间应该花在更有价值的事情之上，因此废弃，感谢关注和表示抱歉！

**Comment by goodluckforme** [comment]
var currentClazz = Any()

    fun toGetAmapLocation(calzz: Any) {
        if (amapLocation != null) {
            Mailbox.getInstance().post(Mail(amapLocation, calzz::class.java))
        } else {
            mLocationClient?.startLocation()
        }
        currentClazz = calzz
    }
好吧 。但是如上所写 即可实现我要的需求
